import Head from "next/head";
import Footer from "./footer";
import NavMenu from "./navmenu";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>1Ethereum</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#563d7c" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="d-flex w-100 h-100 p-3 mx-auto flex-column">
        <NavMenu />
        <main role="main" className="inner cover">
          {children}
        </main>
        <Footer />
      </div>
    </>
  );
}
